version: '3.8'

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finart-app
    restart: always
    ports:
      - '${PORT:-3001}:3001'
    depends_on:
      - redis
    environment:
      - PORT=${PORT:-3001}
      - NODE_ENV=${NODE_ENV:-development}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - finart-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Redis cache
  redis:
    image: redis:7.0-alpine
    container_name: finart-redis
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - finart-network

networks:
  finart-network:
    driver: bridge

volumes:
  redis-data: 