version: '3.8'

services:
  # Main application in development mode
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Use the development stage
    container_name: finart-app-dev
    restart: always
    ports:
      - '${PORT:-3001}:3001'
    depends_on:
      - redis
    environment:
      - PORT=${PORT:-3001}
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=${DATABASE_URL}
      - PRISMA_QUERY_ENGINE_TYPE=binary
      - PRISMA_CLIENT_ENGINE_TYPE=binary
    networks:
      - finart-network
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./.env:/usr/src/app/.env
      - ./.env.dev:/usr/src/app/.env.dev
    command: npm run start:dev
    
  # Redis cache
  redis:
    image: redis:7.0-alpine
    container_name: finart-redis-dev
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data-dev:/data
    networks:
      - finart-network

networks:
  finart-network:
    driver: bridge

volumes:
  redis-data-dev: 